presubmits:
- always_run: true
  context: op1st/prow/pre-commit
  decorate: true
  name: pre-commit
  skip_report: false
  spec:
    containers:
    - command:
      - pre-commit
      - run
      - --from-ref
      - HEAD@{1}
      - --to-ref
      - HEAD
      image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
