host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pip

runtime_environments:
- name: rhel-8
  operating_system:
    name: rhel
    version: "8.0"
  python_version: "3.8"
  recommendation_type: latest

managers:
- name: version
  configuration:
    maintainers:
    - goern
    - fridex
    assignees:
    - sesheta
    labels: [bot]
    changelog_file: false
