units:
  wraps:
  - name: AioesphomeapiGitHubPopularityWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: aioesphomeapi
    run:
      justification:
      - type: INFO
        message: Project 'aioesphomeapi' has high popularity on GitHub
        link: https://github.com/esphome/aioesphomeapi
        package_name: aioesphomeapi
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.7.4
