units:
  wraps:
  - name: AioesphomeapiGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: aioesphomeapi
    run:
      release_notes:
        organization: esphome
        repository: aioesphomeapi
        tag_version_prefix: v
