units:
  wraps:
  - name: Aioesphomeapi915PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: aioesphomeapi
          version: ==9.1.5
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'aioesphomeapi' in version
          '9.1.5' can have up to 44.42KiB
        link: https://pypi.org/project/aioesphomeapi/9.1.5/#files
        package_name: aioesphomeapi
