units:
  wraps:
  - name: DockerComposeGitHubPopularityWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: docker-compose
    run:
      justification:
      - type: INFO
        message: Project 'docker-compose' has very high popularity on GitHub
        link: https://github.com/docker/compose
        package_name: docker-compose
