units:
  wraps:
  - name: PytestDockerCompose321PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: pytest-docker-compose
          version: ==3.2.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'pytest-docker-compose' in version
          '3.2.1' can have up to 14.95KiB
        link: https://pypi.org/project/pytest-docker-compose/3.2.1/#files
        package_name: pytest-docker-compose
