units:
  wraps:
  - name: BinaryArtifactsAnsibleScoreCardsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: ansible
    run:
      justification:
      - type: WARNING
        message: Project has binary artifacts in the source repository
        link: https://github.com/ossf/scorecard/blob/main/docs/checks.md
        package_name: ansible
