units:
  wraps:
  - name: MoleculeGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
    run:
      release_notes:
        organization: ansible-community
        repository: molecule
        tag_version_prefix: v
