units:
  wraps:
  - name: Moleculex1x20x1PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==1.20.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '1.20.1' can have up to 4.96MiB
        link: https://pypi.org/project/molecule/1.20.1/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex1x20x3PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==1.20.3
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '1.20.3' can have up to 4.96MiB
        link: https://pypi.org/project/molecule/1.20.3/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex1x21x1PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==1.21.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '1.21.1' can have up to 4.96MiB
        link: https://pypi.org/project/molecule/1.21.1/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex1x22x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==1.22.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '1.22.0' can have up to 4.96MiB
        link: https://pypi.org/project/molecule/1.22.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex1x23x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==1.23.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '1.23.0' can have up to 4.96MiB
        link: https://pypi.org/project/molecule/1.23.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex1x25x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==1.25.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '1.25.0' can have up to 4.96MiB
        link: https://pypi.org/project/molecule/1.25.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex1x25x1PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==1.25.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '1.25.1' can have up to 4.96MiB
        link: https://pypi.org/project/molecule/1.25.1/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x10x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.10.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.10.0' can have up to 4.29MiB
        link: https://pypi.org/project/molecule/2.10.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x10x1PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.10.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.10.1' can have up to 4.29MiB
        link: https://pypi.org/project/molecule/2.10.1/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x11x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.11.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.11.0' can have up to 4.29MiB
        link: https://pypi.org/project/molecule/2.11.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x12x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.12.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.12.0' can have up to 4.30MiB
        link: https://pypi.org/project/molecule/2.12.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x12x1PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.12.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.12.1' can have up to 4.29MiB
        link: https://pypi.org/project/molecule/2.12.1/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x13x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.13.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.13.0' can have up to 4.30MiB
        link: https://pypi.org/project/molecule/2.13.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x13x1PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.13.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.13.1' can have up to 4.30MiB
        link: https://pypi.org/project/molecule/2.13.1/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x14x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.14.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.14.0' can have up to 4.30MiB
        link: https://pypi.org/project/molecule/2.14.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x15x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.15.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.15.0' can have up to 4.30MiB
        link: https://pypi.org/project/molecule/2.15.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x16x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.16.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.16.0' can have up to 4.31MiB
        link: https://pypi.org/project/molecule/2.16.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x17x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.17.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.17.0' can have up to 4.31MiB
        link: https://pypi.org/project/molecule/2.17.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x18x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.18.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.18.0' can have up to 4.31MiB
        link: https://pypi.org/project/molecule/2.18.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x18x1PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.18.1
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.18.1' can have up to 4.31MiB
        link: https://pypi.org/project/molecule/2.18.1/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
  - name: Moleculex2x19x0PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: molecule
          version: ==2.19.0
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'molecule' in version
          '2.19.0' can have up to 4.31MiB
        link: https://pypi.org/project/molecule/2.19.0/#files
        package_name: molecule
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
