units:
  wraps:
  - name: TasksGitHubContributorsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: tasks
    run:
      justification:
      - type: WARNING
        message: Package 'tasks' has less than 5 contributors on GitHub
        link: https://github.com/pb-/tasks
        package_name: tasks
