units:
  wraps:
  - name: TasksGitHubPopularityWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: tasks
    run:
      justification:
      - type: WARNING
        message: Project 'tasks' has low popularity on GitHub
        link: https://github.com/pb-/tasks
        package_name: tasks
