units:
  wraps:
  - name: Tasks280PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: tasks
          index_url: "https://pypi.org/simple"
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'tasks' in version
          '2.8.0' can have up to 12.17KiB
        link: https://pypi.org/project/tasks/2.8.0/#files
        package_name: tasks
