units:
  wraps:
  - name: AutomaticDependencyUpdatePrometheusFlaskExporterScoreCardsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-flask-exporter
    run:
      justification:
      - type: WARNING
        message: Project does NOT use tools for automatic dependency updates based on Security Scorecards
        link: https://github.com/ossf/scorecard/blob/main/docs/checks.md
        package_name: prometheus-flask-exporter
