units:
  wraps:
  - name: PrometheusClientGitHubPopularityWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-client
    run:
      justification:
      - type: INFO
        message: Project 'prometheus-client' has very high popularity on GitHub
        link: https://github.com/prometheus/client_python
        package_name: prometheus-client
