units:
  wraps:
  - name: PrometheusxClientGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-client
    run:
      release_notes:
        organization: prometheus
        repository: client_python
        tag_version_prefix: v
