units:
  wraps:
  - name: PrometheusClient090PyPIArtifactSizeWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-client
          index_url: "https://pypi.org/simple"
    run:
      justification:
      - type: INFO
        message: >-
          Installed artifact size for package 'prometheus-client' in version
          '0.9.0' can have up to 66.65KiB
        link: https://pypi.org/project/prometheus-client/0.9.0/#files
        package_name: prometheus-client
