units:
  wraps:
  - name: ActivePrometheusClientScoreCardsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-client
    run:
      justification:
      - type: WARNING
        message: Project is NOT actively maintained based on Security Scorecards
        link: https://github.com/ossf/scorecard/blob/main/docs/checks.md
        package_name: prometheus-client
