units:
  wraps:
  - name: PrometheusClientTopPackageNamesWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-client
    run:
      justification:
      - type: INFO
        message: Package 'prometheus-client' is popular within Thoth community
        link: thoth_community
        package_name: prometheus-client
