units:
  wraps:
  - name: DockerGitHubPopularityWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: docker
    run:
      justification:
      - type: INFO
        message: Project 'docker' has very high popularity on GitHub
        link: https://github.com/docker/docker-py
        package_name: docker
