units:
  wraps:
  - name: KubernetesGitHubURLWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: kubernetes
    run:
      justification:
      - type: INFO
        message: Package 'kubernetes' is hosted on GitHub
        link: https://github.com/kubernetes-client/python
        package_name: kubernetes
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
