units:
  wraps:
  - name: KubernetesGitHubPopularityWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: kubernetes
    run:
      justification:
      - type: INFO
        message: Project 'kubernetes' has very high popularity on GitHub
        link: https://github.com/kubernetes-client/python
        package_name: kubernetes
