units:
  wraps:
  - name: KubernetesPyPIMaintainerProjectsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: kubernetes
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: WARNING
        message: >-
          Project 'kubernetes' is maintained by maintainers that maintain small
          number of projects on PyPI (less than 3)
        link: https://pypi.org/project/kubernetes/
        package_name: kubernetes
