units:
  wraps:
  - name: KubernetesTopPackageNamesWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: kubernetes
    run:
      justification:
      - type: INFO
        message: Package 'kubernetes' is popular within Thoth community
        link: thoth_community
        package_name: kubernetes
